# -*- coding: utf-8 -*-
"""bruteForce.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t1AcWRlXIYDM88oB8US66GYiFjeauyV9
"""

import itertools
import string
import time

# Kullanıcıdan şifreyi alıyoruz ve boşlukları temizliyoruz
target_password = input("Hedef şifreyi girin (küçük harf): ").strip()

# Kullanılacak karakterler
chars = string.ascii_lowercase

# Başlangıç zamanını kaydet
start_time = time.time()

# Maksimum şifre uzunluğu
max_length = len(target_password)  # sadece gereken uzunlukta arama yapar

# Deneme sayacı
attempts = 0

# Belirlenen uzunluktaki kombinasyonları sırayla deniyoruz
for attempt in itertools.product(chars, repeat=max_length):
    guess = ''.join(attempt)
    attempts += 1

    if guess == target_password:
        print(f"✅ Şifre bulundu: {guess}")
        print(f"🔢 Deneme sayısı: {attempts}")
        print(f"⏱️ Süre: {round(time.time() - start_time, 2)} saniye")
        break
else:
    print("❌ Şifre bulunamadı.")

